# Generated by Django 5.0 on 2023-12-29 08:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedApp', '0002_rename_messages_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
