# Generated by Django 5.0 on 2023-12-29 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedApp', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='msg',
            new_name='post',
        ),
    ]
